import { decimal, int, json, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";
import { relations } from "drizzle-orm";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Financial profile for each user.
 * Stores core financial information collected during onboarding.
 */
export const financialProfiles = mysqlTable("financial_profiles", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  monthlyIncome: decimal("monthlyIncome", { precision: 12, scale: 2 }).notNull(),
  incomeType: mysqlEnum("incomeType", ["fixed", "variable"]).notNull(),
  hasFixedExpenses: int("hasFixedExpenses").notNull(), // 0 or 1 (boolean)
  fixedExpensesAmount: decimal("fixedExpensesAmount", { precision: 12, scale: 2 }),
  hasDebts: int("hasDebts").notNull(), // 0 or 1 (boolean)
  totalDebts: decimal("totalDebts", { precision: 12, scale: 2 }),
  currentSavings: decimal("currentSavings", { precision: 12, scale: 2 }),
  riskProfile: mysqlEnum("riskProfile", ["conservative", "moderate", "aggressive"]).default("moderate"),
  investmentExperience: mysqlEnum("investmentExperience", ["beginner", "intermediate", "advanced"]).default("beginner"),
  completedOnboarding: int("completedOnboarding").default(0).notNull(), // 0 or 1 (boolean)
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type FinancialProfile = typeof financialProfiles.$inferSelect;
export type InsertFinancialProfile = typeof financialProfiles.$inferInsert;

/**
 * Budget allocation based on 50/30/20 model adapted to user profile.
 * Stores the calculated budget breakdown for each user.
 */
export const budgetAllocations = mysqlTable("budget_allocations", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  financialProfileId: int("financialProfileId").notNull(),
  fixedExpensesPercentage: decimal("fixedExpensesPercentage", { precision: 5, scale: 2 }).notNull(),
  fixedExpensesAmount: decimal("fixedExpensesAmount", { precision: 12, scale: 2 }).notNull(),
  variableExpensesPercentage: decimal("variableExpensesPercentage", { precision: 5, scale: 2 }).notNull(),
  variableExpensesAmount: decimal("variableExpensesAmount", { precision: 12, scale: 2 }).notNull(),
  savingsPercentage: decimal("savingsPercentage", { precision: 5, scale: 2 }).notNull(),
  savingsAmount: decimal("savingsAmount", { precision: 12, scale: 2 }).notNull(),
  investmentPercentage: decimal("investmentPercentage", { precision: 5, scale: 2 }).notNull(),
  investmentAmount: decimal("investmentAmount", { precision: 12, scale: 2 }).notNull(),
  debtPaymentPercentage: decimal("debtPaymentPercentage", { precision: 5, scale: 2 }).notNull(),
  debtPaymentAmount: decimal("debtPaymentAmount", { precision: 12, scale: 2 }).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type BudgetAllocation = typeof budgetAllocations.$inferSelect;
export type InsertBudgetAllocation = typeof budgetAllocations.$inferInsert;

/**
 * Financial plan generated by AI with personalized analysis and recommendations.
 */
export const financialPlans = mysqlTable("financial_plans", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  financialProfileId: int("financialProfileId").notNull(),
  currentSituation: text("currentSituation").notNull(),
  problemsIdentified: text("problemsIdentified").notNull(),
  recommendations: text("recommendations").notNull(),
  actionPlan: text("actionPlan").notNull(),
  generatedAt: timestamp("generatedAt").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type FinancialPlan = typeof financialPlans.$inferSelect;
export type InsertFinancialPlan = typeof financialPlans.$inferInsert;

/**
 * Investment goals and targets for the user.
 */
export const investmentGoals = mysqlTable("investment_goals", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  goalName: varchar("goalName", { length: 255 }).notNull(),
  targetAmount: decimal("targetAmount", { precision: 12, scale: 2 }).notNull(),
  timelineYears: int("timelineYears").notNull(),
  monthlyInvestment: decimal("monthlyInvestment", { precision: 12, scale: 2 }).notNull(),
  expectedAnnualReturn: decimal("expectedAnnualReturn", { precision: 5, scale: 2 }).default("7.00"),
  currentAmount: decimal("currentAmount", { precision: 12, scale: 2 }).default("0"),
  status: mysqlEnum("status", ["active", "completed", "paused"]).default("active"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type InvestmentGoal = typeof investmentGoals.$inferSelect;
export type InsertInvestmentGoal = typeof investmentGoals.$inferInsert;

/**
 * Chat conversations with AI assistant.
 */
export const chatConversations = mysqlTable("chat_conversations", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  messages: json("messages").notNull(), // Array of {role, content} objects
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ChatConversation = typeof chatConversations.$inferSelect;
export type InsertChatConversation = typeof chatConversations.$inferInsert;

// Relations
export const usersRelations = relations(users, ({ many }) => ({
  financialProfiles: many(financialProfiles),
  budgetAllocations: many(budgetAllocations),
  financialPlans: many(financialPlans),
  investmentGoals: many(investmentGoals),
  chatConversations: many(chatConversations),
}));

export const financialProfilesRelations = relations(financialProfiles, ({ one, many }) => ({
  user: one(users, {
    fields: [financialProfiles.userId],
    references: [users.id],
  }),
  budgetAllocations: many(budgetAllocations),
  financialPlans: many(financialPlans),
}));

export const budgetAllocationsRelations = relations(budgetAllocations, ({ one }) => ({
  user: one(users, {
    fields: [budgetAllocations.userId],
    references: [users.id],
  }),
  financialProfile: one(financialProfiles, {
    fields: [budgetAllocations.financialProfileId],
    references: [financialProfiles.id],
  }),
}));

export const financialPlansRelations = relations(financialPlans, ({ one }) => ({
  user: one(users, {
    fields: [financialPlans.userId],
    references: [users.id],
  }),
  financialProfile: one(financialProfiles, {
    fields: [financialPlans.financialProfileId],
    references: [financialProfiles.id],
  }),
}));

export const investmentGoalsRelations = relations(investmentGoals, ({ one }) => ({
  user: one(users, {
    fields: [investmentGoals.userId],
    references: [users.id],
  }),
}));

export const chatConversationsRelations = relations(chatConversations, ({ one }) => ({
  user: one(users, {
    fields: [chatConversations.userId],
    references: [users.id],
  }),
}));

/**
 * Transaction history for tracking user spending and income.
 */
export const transactions = mysqlTable("transactions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  type: mysqlEnum("type", ["income", "expense", "savings", "investment"]).notNull(),
  category: varchar("category", { length: 100 }).notNull(),
  amount: decimal("amount", { precision: 12, scale: 2 }).notNull(),
  description: text("description"),
  transactionDate: timestamp("transactionDate").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Transaction = typeof transactions.$inferSelect;
export type InsertTransaction = typeof transactions.$inferInsert;

export const transactionsRelations = relations(transactions, ({ one }) => ({
  user: one(users, {
    fields: [transactions.userId],
    references: [users.id],
  }),
}));
